version: '3.4'

services:

  ordersqlserver:
    environment:
      - SA_PASSWORD=pa55w0rd!
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - ordersqlvolume:/var/opt/mssql

  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
    ports:
      - "8000:80"

  basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CacheSettings:ConnectionString=basketdb:6379
      - "GrpcSettings:DiscountUrl=http://discount.grpc"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    ports:
      - "8001:80"
    depends_on:
      - rabbitmq

  discount.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDB;Userid=admin;Password=admin1234;"
    ports:
      - "8002:80"

  discount.grpc:
    container_name: discount.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDB;Userid=admin;Password=admin1234;"
    ports:
      - "8003:80"

  ordering.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:OrderingConnectionString=Data Source=ordersqlserver,1433;Database=OrderDB;User ID=sa;Password=pa55w0rd!"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    depends_on:
      - ordersqlserver
      - rabbitmq
    ports:
      - "8004:80"

  rabbitmq:
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672" 