version: '3.4'

services:
  catalogdb:
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  basketdb:
    restart: always
    ports:
      - "6379:6379"

  discountdb:
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=DiscountDB
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  portainer:
    restart: always
    ports:
      - "8090:8000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
    ports:
      - "8000:80"
    depends_on:
      - catalogdb

  mongoclient:
    image: mongoclient/mongoclient
    ports:
      - "3000:3000"
    depends_on:
      - catalogdb

  basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CacheSettings:ConnectionString=basketdb:6379
    depends_on:
      - basketdb
    ports:
      - "8001:80"

  pgadmin:
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@aspnetrun.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
      - "5050:80"

  discount.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDB;Userid=admin;Password=admin1234;"
    depends_on:
      - discountdb
    ports:
      - "8002:80"

